---
galaxy_info:
  author: Manuel Tiago Pereira
  description: Ansible role for host basic and common configuration.
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: EL
    versions:
    - all
  categories:
    - system
dependencies: []

