---
- hosts: all
  sudo: yes

  vars_files:
    - defaults/main.yml

  vars:
    common_pkg_purge: yes
    common_repo_deb:
      - url: 'http://ftp.rnl.ist.utl.pt/pub/debian'
        codename: "wheezy"
        components: 'main'
    common_repo_deb_keys:
      - url: 'https://ftp-master.debian.org/keys/archive-key-6.0.asc'
        id: '473041FA'
    common_pkg_remove_list_deb:
      - exim4

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: test - remove swap if present
      command: swapoff -a
      when: ansible_swaptotal_mb != 0
      register: common_test_swapoff
      sudo: yes

    - name: test - regather facts after swap off
      action: setup
      when: common_test_swapoff.changed

    - include: tasks/main.yml
