---
- name: ntp - Install ntp in RedHat
  yum: pkg=ntpd state={{ common_pkg_state }}
  when: ansible_os_family == 'RedHat'

- name: ntp - Configure ntp
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - ntp - restart ntpd

- name: ntp - Enable ntp
  service: name=ntpd state=running enabled=yes
